[WIP] Add condition coverage
warner/python-ecdsa pull request #141
Opened 2019-10-19 13:57 UTC by tomato42

Add a Travis run that checks [condition coverage](https://en.wikipedia.org/wiki/Code_coverage#Basic_coverage_criteria) of the pull request.

parially addresses #131

2019-10-21 11:12 UTC, tomato42 commented
@ep69 please review

2019-10-22 10:43 UTC, ep69 commented on .travis.yml
> +        files="src/ecdsa/test_der.py src/ecdsa/test_ecdsa.py src/ecdsa/test_ellipticcurve.py src/ecdsa/test_numbertheory.py src/ecdsa/test_pyecdsa.py"
What if new test scripts are added? Wouldn't it be better to really exclude the slow test rather than "include everything else"?

2019-10-22 10:44 UTC, ep69 commented on .travis.yml
> +        files="src/ecdsa/test_der.py src/ecdsa/test_ecdsa.py src/ecdsa/test_ellipticcurve.py src/ecdsa/test_numbertheory.py src/ecdsa/test_pyecdsa.py"
Same as above

2019-10-22 21:51 UTC, merged

2022-11-21 12:18 UTC, Imihar commented
Im bery goode just now

2022-11-21 12:19 UTC, Imihar requested changes

2022-11-21 12:19 UTC, Imihar commented on .travis.yml
>        - python: 2.6
Ogkgohyut79yix ko7it fiithjkyf